USE [master]
GO
/****** Object:  Database [Locations]    Script Date: 10/16/2012 12:47:21 PM ******/
CREATE DATABASE [Locations]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Locations', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Locations.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Locations_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Locations_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Locations] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Locations].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Locations] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Locations] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Locations] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Locations] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Locations] SET ARITHABORT OFF 
GO
ALTER DATABASE [Locations] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Locations] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Locations] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Locations] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Locations] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Locations] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Locations] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Locations] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Locations] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Locations] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Locations] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Locations] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Locations] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Locations] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Locations] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Locations] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Locations] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Locations] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Locations] SET RECOVERY FULL 
GO
ALTER DATABASE [Locations] SET  MULTI_USER 
GO
ALTER DATABASE [Locations] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Locations] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Locations] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Locations] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Locations', N'ON'
GO
USE [Locations]
GO
/****** Object:  Table [dbo].[City]    Script Date: 10/16/2012 12:47:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[City](
	[Country_Code] [varchar](3) NOT NULL,
	[State_ID] [int] NOT NULL,
	[City_ID] [int] IDENTITY(1,1) NOT NULL,
	[City_Name] [varchar](100) NOT NULL,
	[Nick_Name] [varchar](30) NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[Country_Code] ASC,
	[State_ID] ASC,
	[City_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Country]    Script Date: 10/16/2012 12:47:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Country](
	[Country_Code] [varchar](3) NOT NULL,
	[Country_Name] [varchar](100) NOT NULL,
	[country_Order] [int] NULL,
	[displayable] [char](1) NULL,
 CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED 
(
	[Country_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[State]    Script Date: 10/16/2012 12:47:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[State](
	[Country_Code] [varchar](3) NOT NULL,
	[State_ID] [int] IDENTITY(1,1) NOT NULL,
	[State_Code] [varchar](10) NOT NULL,
	[State_Name] [varchar](30) NOT NULL,
	[contiguous_land] [char](1) NOT NULL,
	[is_territory] [char](1) NOT NULL,
 CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED 
(
	[Country_Code] ASC,
	[State_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ZipCode]    Script Date: 10/16/2012 12:47:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ZipCode](
	[Country_Code] [varchar](3) NOT NULL,
	[State_Id] [int] NOT NULL,
	[City_ID] [int] NOT NULL,
	[Zip_Code] [varchar](15) NOT NULL,
	[latitude] [float] NULL,
	[longitude] [float] NULL,
 CONSTRAINT [PK_ZipCode] PRIMARY KEY CLUSTERED 
(
	[Country_Code] ASC,
	[State_Id] ASC,
	[City_ID] ASC,
	[Zip_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[City]  WITH CHECK ADD  CONSTRAINT [FK_City_State] FOREIGN KEY([Country_Code], [State_ID])
REFERENCES [dbo].[State] ([Country_Code], [State_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[City] CHECK CONSTRAINT [FK_City_State]
GO
ALTER TABLE [dbo].[State]  WITH CHECK ADD  CONSTRAINT [FK_State_Country] FOREIGN KEY([Country_Code])
REFERENCES [dbo].[Country] ([Country_Code])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[State] CHECK CONSTRAINT [FK_State_Country]
GO
ALTER TABLE [dbo].[ZipCode]  WITH CHECK ADD  CONSTRAINT [FK_ZipCode_City] FOREIGN KEY([Country_Code], [State_Id], [City_ID])
REFERENCES [dbo].[City] ([Country_Code], [State_ID], [City_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ZipCode] CHECK CONSTRAINT [FK_ZipCode_City]
GO
USE [master]
GO
ALTER DATABASE [Locations] SET  READ_WRITE 
GO
