//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationSolution.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.ZipCodes = new HashSet<ZipCode>();
        }
    
        public string CountyCode { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string NickName { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<ZipCode> ZipCodes { get; set; }
    }
}
