//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationSolution.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public string CountyCode { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
        public string Zip { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual City City { get; set; }
    }
}
